name: job_order_management
description: A comprehensive Job Order Management System for multi-user mobile applications.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  
  # State management
  flutter_riverpod: ^3.0.3
  
  # Navigation
  go_router: ^16.2.5
  
  # Supabase
  supabase_flutter: ^2.3.3
  
  # Push notifications
  onesignal_flutter: ^5.0.4
  
  # Image handling
  image: ^4.1.3
  image_picker: ^1.0.4
  
  # Barcode scanning
  mobile_scanner: ^7.1.2
  
  # PDF generation
  pdf: ^3.10.4
  
  # Printing
  printing: ^5.12.0
  # bluetooth_print: ^4.3.0  # Temporarily commented out due to build issues
  
  # CSV handling
  csv: ^6.0.0
  
  # Local storage for offline
  # isar: ^3.1.0+1  # Temporarily commented out due to build issues
  # isar_flutter_libs: ^3.1.0+1  # Temporarily commented out due to build issues
  
  # HTTP requests
  http: ^1.1.2
  
  # Environment variables
  flutter_dotenv: ^6.0.0
  
  # Date/time handling
  table_calendar: ^3.0.9
  
  # Forms
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  
  # UI components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Signature capture
  signature: ^6.3.0
  
  # Permission handling
  permission_handler: ^12.0.1
  
  # Device info
  device_info_plus: ^12.2.0
  
  # Path handling
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
